<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <!-- The tests deliberately use obsolete definitions. -->
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Nova.OpenTelemetry.SemanticConventions/Nova.OpenTelemetry.SemanticConventions.csproj" />
    <ProjectReference Include="../../src/Nova.OpenTelemetry.SemanticConventions.Incubating/Nova.OpenTelemetry.SemanticConventions.Incubating.csproj" />
  </ItemGroup>

</Project>
